---
- name: Localhost
  hosts: localhost
  remote_user: anamikamishra
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "anunik24/calculator-docker-image"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Delete container if present
      shell: docker rm -f calculator-java
      ignore_errors: true

    - name: Running container
      shell: docker run -it -d --name calculator-java anunik24/calculator-docker-image
