---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: anamikamishra
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "anunik24/calculator-docker-image"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Check if calculator-java container exists
      command: docker ps -a --filter "name=calculator-java" --format "{{.Names}}"
      register: container_exists

    - name: Stop and remove calculator-java container if it exists
      docker_container:
        name: calculator-java
        state: absent
      when: container_exists.stdout_lines | length > 0

    - name: Run calculator-java container
      docker_container:
        name: calculator-java
        image: anunik24/calculator-docker-image
        detach: yes
